/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#586064",
        "tertiary-fixed": "#e3dbfd",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#334052",
        "primary": "#0c56d0",
        "on-secondary-container": "#465365",
        "on-background": "#2b3437",
        "on-tertiary": "#fcf7ff",
        "secondary-fixed-dim": "#c8d5ec",
        "error-container": "#fe8983",
        "on-surface": "#2b3437",
        "tertiary-container": "#e3dbfd",
        "on-tertiary-fixed": "#3f3a54",
        "on-tertiary-container": "#524c68",
        "on-secondary": "#f8f8ff",
        "surface-container": "#eaeff1",
        "surface-container-high": "#e2e9ec",
        "primary-fixed": "#dae2ff",
        "outline-variant": "#abb3b7",
        "surface-variant": "#dbe4e7",
        "tertiary-dim": "#554f6b",
        "primary-dim": "#004aba",
        "on-primary-container": "#004ab9",
        "inverse-on-surface": "#9b9d9e",
        "surface-tint": "#0c56d0",
        "tertiary-fixed-dim": "#d5cdee",
        "inverse-primary": "#5c8bff",
        "secondary-container": "#d6e3fb",
        "error-dim": "#4e0309",
        "surface-container-low": "#f1f4f6",
        "primary-container": "#dae2ff",
        "error": "#9f403d",
        "on-primary-fixed-variant": "#0253cd",
        "background": "#f8f9fa",
        "secondary": "#536073",
        "outline": "#737c7f",
        "primary-fixed-dim": "#c6d3ff",
        "on-primary-fixed": "#003993",
        "on-primary": "#f8f7ff",
        "on-error-container": "#752121",
        "tertiary": "#615b77",
        "on-tertiary-fixed-variant": "#5c5672",
        "inverse-surface": "#0c0f10",
        "on-secondary-fixed-variant": "#4f5c70",
        "surface-dim": "#d1dce0",
        "on-error": "#fff7f6",
        "surface-container-highest": "#dbe4e7",
        "secondary-fixed": "#d6e3fb",
        "secondary-dim": "#475467",
        "surface-bright": "#f8f9fa",
        "surface": "#f8f9fa"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
